### ISSUE TITLE
LaTeX workshop RSVP 

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/latex#1]
# To RSVP, include your name in your comment below.

The workshop will be on Thursday, November 11 from 4-6p in CS150/151, open to everyone, led by @cibelemf.

Please fill out this short pre-workshop survey before the workshop: http://goo.gl/forms/vaQoHG4Hl3.

If you don't have access to a *nix machine or you're not sure if your Mac is setup with brew, check out [our bootcamp instructions](http://github.com/CSWomenUMass/bootcamp). If you have time to look at this before the workshop, you won't have to spend any time downloading and installing during the workshop. **This is particularly important for LaTeX** 

Feel free to ask questions here or [on Slack](http:/cswomen.slack.com/signup).

**Comment by jjfiv** [comment]
John Foley is attending.

**Comment by etosch** [comment]
:dragon:  Emma Tosch :beers:

**Comment by ThienDinh** [comment]
Thien Dinh is going.

**Comment by AruniRC** [comment]
Aruni RoyChowdhury is NOT attending. 
I have a lab meeting. Apologies for the last-minute cancellation.

**Comment by emoshkovich** [comment]
Eva Moscovici is attending

**Comment by kepingbi** [comment]
Keping Bi is attending.

**Comment by strubell** [comment]
I'll be there!

**Comment by etosch** [comment]
@strubell : What is your name?

**Comment by strubell** [comment]
oops -- Emma Strubell

**Comment by Sandhya0204** [comment]
Sandhya Sankaranarayanan attending!

**Comment by pmandler** [comment]
Pam Mandler has much to learn about LaTeX.

**Comment by rolivia** [comment]
Rian Shambaugh is going

**Comment by craigSgreenberg** [comment]
Craig Greenberg will be there! :snail:

**Comment by ChenyunWu** [comment]
Chenyun Wu is going!

**Comment by mainkhan** [comment]
Main Khan is going!

**Comment by MishraPuja** [comment]
Puja Mishra wants to attend this session !

**Comment by myatnoe** [comment]
Michelle Chan is going!!

**Comment by tasnani** [comment]
Me and my friend, Stefan Grosser are coming.

**Comment by etosch** [comment]
@tasnani : What is your name?

**Comment by tasnani** [comment]
@etosch Tanaya Asnani

**Comment by belindanju** [comment]
I am Tian Guo, and I will be there.

**Comment by kdricci** [comment]
Kathryn Ricci is going

**Comment by Shamya** [comment]
I am Shamya and I will be there.

**Comment by poddarh** [comment]
Harsh Poddar will be there!

**Comment by mmcmahon13** [comment]
Molly McMahon will be there (for real this time). I need to leave at 5:30 though

**Comment by RoseTharailJohn** [comment]
will be coming!

**Comment by matthew-dews** [comment]
Will be there

**Comment by etosch** [comment]
@matthew-dews What is your name?

**Comment by shaylyna** [comment]
Shaylyn Adams

**Comment by etosch** [comment]
@RoseTharailJohn What is your name?

**Comment by RoseTharailJohn** [comment]
@etosch  it is : Rose Tharail John

**Comment by bpowers** [comment]
I'd like to attend: Bobby Powers

**Comment by cibelemf** [comment]
Cibele Freire will be there!

**Comment by etosch** [comment]
@AruniRC That's too bad! Next time?

**Comment by ameetrivedi** [comment]
Amee Trivedi will be there with Neil Meckoni

**Comment by etosch** [comment]
Everyone: please fill out the post-workshop survey: http://goo.gl/forms/hsWQ2un1P1

**Comment by etosch** [comment]
@bpowers @RoseTharailJohn @shaylyna @ThienDinh @emoshkovich @kdricci @kepingbi @craigSgreenberg @pmandler @Sandhya0204 @rolivia @LucyGoGo @mainkhan @MishraPuja @myatnoe @tasnani @poddarh @mmcmahon13 @matthew-dews 

If you have not yet filled out the post-workshop survey, please do so: http://goo.gl/forms/2nelzHahYg
